---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kube-noah
  namespace: kube-system
  labels:
    app: kube-noah
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: kube-noah
          restartPolicy: OnFailure
          containers:
          - name: kube-noah
            image: gefenonline/kube-noah
            env:
            - name: BACKUP
              value: 'true'
            - name: GIT_REPO_URL
              valueFrom:
                secretKeyRef:
                  name: env-vars
                  key: KUBE_ARK_REPO_URL
            - name: KUBE_CLUSTER_NAME
              valueFrom:
                secretKeyRef:
                  name: env-vars
                  key: KUBE_CLUSTER_NAME