---
apiVersion: batch/v1
kind: Job
metadata:
  name: kube-noah
  namespace: kube-system
  labels:
    app: kube-noah
spec:
  backoffLimit: 4
  template:
    spec:
      serviceAccountName: kube-noah
      restartPolicy: Never
      containers:
      - name: kube-noah
        image: gefenonline/kube-noah
        env:
        - name: RESTORE
          value: 'true'
        - name: GIT_REPO_URL
          valueFrom:
            secretKeyRef:
              name: env-vars
              key: KUBE_ARK_REPO_URL
        - name: KUBE_CLUSTER_NAME
          valueFrom:
            secretKeyRef:
              name: env-vars
              key: KUBE_CLUSTER_NAME