---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kube-noah 
rules:
  - apiGroups:
      - ""
    resources:
      - ""
    verbs:
      - list
      - watch
      - get
      - update
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kube-noah
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-noah
subjects:
  - kind: ServiceAccount
    name: kube-noah
    namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-noah
  namespace: kube-system